In [1]:
%pip install torch

  Using cached filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached fsspec-2025.10.0-py3-none-any.whl.metadata (10 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached markupsafe-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 MB 22.2 MB/s  0:00:03m0:00:0100:01
Using cached fsspec-2025.10.0-py3-none-any.whl (200 kB)
Using cached networkx-3.5-py3-none-any.whl (2.0 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached filelock-3.20

In [4]:
import torch

x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [ ]:
torch.rand(2,3) # Zufallszahlen

tensor([[0.5301, 0.4247, 0.3784],
        [0.7258, 0.1183, 0.0605]])

In [6]:
torch.zeros(1,2)

tensor([[0., 0.]])

In [7]:
ones_tensor = torch.ones(2,3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
x + ones_tensor

tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [9]:
a = torch.tensor([[1., 2], [3,4]]) 
b = torch.tensor([[5., 6], [7,8]]) 
torch.matmul(a,b)
a @ b

tensor([[19., 22.],
        [43., 50.]])

In [ ]:
a*b #elementenweise 

tensor([[ 5., 12.],
        [21., 32.]])

In [11]:
a.sum()

tensor(10.)

In [12]:
a.mean()

tensor(2.5000)

In [13]:
# cpu, cuda, mps (Apple Silicon)

if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

device = torch.device("mps") # für Apple Silicon 
device

device(type='mps')

In [ ]:
import torch.nn as nn # Neuronale Netze
import torch.optim as optim # Optimierer
# 10 Eingänge, 1 Ausgang -> Fully-connected feed-forward neural network
NN = nn.Linear(10,1) # im Tensorflow -> Dense 
# MLP, P -> Multi-layer Perceptron (old-school)
# in Publikationen: FC, FFN, FFNN 
loss = nn.MSELoss() # Kostenfunktion, Verlustfunktion
# loss, cost, criterion, crit
optimizer = optim.SGD(NN.parameters(), lr = 1e-2 ) # Stochastic Gradient Descent
# lr = Lernrate (eta, alpha); NN.parameters() -> Gewichte, Parameter von Modell
input_data = torch.randn(10) # zufällige Daten (X)
output = NN(input_data) # y_pred, y_hat -> Modell 
y = torch.ones(1) # target, bzw. wir möchten, dass NN eine 1 ausgibt -> Realität, y_true
loss_output = loss(output, y) # Unterschied zwischen Modell und Realität , Anfangswert der Kostenfunktion

print(f"Kosten: {loss_output:.2} (vor Update)")

# zwei magische Zeilen (Gradientenabstiegsmethode)
loss_output.backward() # Gradienten berechnen
optimizer.step() # Update-Schritt 
output_new = NN(input_data) # bereits mit neuen Gewichten 
loss_new = loss(output_new,y) # Wert der Kostenfunktion nach Update
print(f"Kosten: {loss_new:.2} (nach Update)")

Kosten: 1.7 (vor Update)
Kosten: 0.54 (nach Update)
